services:
    app:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            target: development

        restart: unless-stopped
        command: npm run start:dev
        ports:
            - '3000:3000'
        volumes:
            - .:/app
        depends_on:
            - database
        env_file:
            - dev.env

    database:
        container_name: postgres
        image: postgres:16-alpine
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data
        env_file:
            - dev.env
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=postgres

volumes:
    postgres-data:
