services:
    app:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            target: production

        restart: unless-stopped
        ports:
            - '3000:3000'
        env_file:
            - prod.env
